Repository scrum-til-i-die/TheCut, pull requests merged in 2020-03, with the labels that each got.

#45 removed documentation from git repo
  documentation /DevelopmentProcess.tex
  documentation /FinalDemoContract.tex
  documentation /HazardAnalysis.tex
  documentation /ProjectGoals.tex
  documentation /SystemDesign.tex
  documentation /SystemRequirements.tex
  documentation /img/HazardAnalysis/ComponentDiagram.png
  documentation /img/SystemDesign/ComponentDiagram.png
  documentation /img/SystemDesign/ContextDiagram.png
  documentation /img/SystemDesign/fd.png
  documentation /img/SystemDesign/stateMachine.png
  documentation /img/SystemDesign/system_decomp.png
  documentation /img/SystemRequirement/contextDiagram.jpg
  documentation /img/SystemRequirement/fd.png
  documentation /img/SystemRequirement/stateMachine.png
Labels: documentation, refactor

#53 Audio process refactor
  server/job_controller/api_services/audio_process.py
  server/job_controller/api_services/video_process.py
  server/job_controller/requirements.txt
Labels: back-end, feature, refactor

#67 Docker-Compose Refactor / Start server shell script
  server/docker-compose.yml
  server/scripts/run_server
  server/scripts/stop_server
Labels: refactor
